/**
 * 错误代码常量
 */

/**
 * 标准错误代码
 */
export const ERROR_CODES = {
  // 协议错误 (PROTOCOL-xxx)
  PROTOCOL_VERSION_MISMATCH: 'PROTOCOL-001',
  PROTOCOL_INVALID_FORMAT: 'PROTOCOL-002',

  // 内核错误 (CORE-xxx)
  CORE_SERVICE_NOT_FOUND: 'CORE-001',
  CORE_ROUTE_FAILED: 'CORE-002',
  CORE_INITIALIZATION_FAILED: 'CORE-003',

  // 权限错误 (PERMISSION-xxx)
  PERMISSION_DENIED: 'PERMISSION-001',
  PERMISSION_INVALID: 'PERMISSION-002',

  // 模块错误 (MODULE-xxx)
  MODULE_NOT_LOADED: 'MODULE-001',
  MODULE_EXECUTION_ERROR: 'MODULE-002',
  MODULE_INVALID_CONFIG: 'MODULE-003',

  // 资源错误 (RESOURCE-xxx)
  RESOURCE_NOT_FOUND: 'RESOURCE-001',
  RESOURCE_ACCESS_FAILED: 'RESOURCE-002',
  RESOURCE_INVALID_URI: 'RESOURCE-003',
  RESOURCE_LOAD_FAILED: 'RESOURCE-004',

  // 验证错误 (VAL-xxx)
  VAL_INVALID_ID: 'VAL-1001',
  VAL_INVALID_CARD_DATA: 'VAL-1002',
  VAL_INVALID_BOX_DATA: 'VAL-1003',
  VAL_INVALID_SCHEMA: 'VAL-1004',
  VAL_REQUIRED_FIELD_MISSING: 'VAL-1005',

  // 系统错误 (SYS-xxx)
  SYS_FILE_NOT_FOUND: 'SYS-9001',
  SYS_FILE_READ_ERROR: 'SYS-9002',
  SYS_FILE_WRITE_ERROR: 'SYS-9003',
  SYS_PARSE_ERROR: 'SYS-9004',
  SYS_NETWORK_ERROR: 'SYS-9005',
  SYS_UNKNOWN_ERROR: 'SYS-9999',
} as const;

/**
 * 错误消息映射（开发时使用key，打包时替换为i18n编码）
 */
export const ERROR_MESSAGES: Record<string, string> = {
  [ERROR_CODES.PROTOCOL_VERSION_MISMATCH]: 'error.protocol_version_mismatch',
  [ERROR_CODES.PROTOCOL_INVALID_FORMAT]: 'error.protocol_invalid_format',
  [ERROR_CODES.CORE_SERVICE_NOT_FOUND]: 'error.service_not_found',
  [ERROR_CODES.CORE_ROUTE_FAILED]: 'error.route_failed',
  [ERROR_CODES.PERMISSION_DENIED]: 'error.permission_denied',
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'error.resource_not_found',
  [ERROR_CODES.RESOURCE_ACCESS_FAILED]: 'error.resource_access_failed',
  [ERROR_CODES.VAL_INVALID_ID]: 'error.invalid_id',
  [ERROR_CODES.VAL_INVALID_CARD_DATA]: 'error.invalid_card_data',
  [ERROR_CODES.SYS_FILE_NOT_FOUND]: 'error.file_not_found',
  [ERROR_CODES.SYS_PARSE_ERROR]: 'error.parse_error',
  [ERROR_CODES.SYS_NETWORK_ERROR]: 'error.network_error',
  [ERROR_CODES.SYS_UNKNOWN_ERROR]: 'error.unknown',
};
